In [23]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_curve
from sklearn.metrics import confusion_matrix


In [ ]:

plt.rc('axes', linewidth = 1.5, labelsize = 14)
plt.rc('xtick', labelsize = 14)
plt.rc('ytick', labelsize = 14)
plt.rc('xtick.major', size = 3, width = 1.5)
plt.rc('ytick.major', size = 3, width = 1.5)

In [2]:
wineData = pd.read_csv('../input/winequality-red.csv')
wineData.head()

fixed acidity  volatile acidity   ...     alcohol  quality
0            7.4              0.70   ...         9.4        5
1            7.8              0.88   ...         9.8        5
2            7.8              0.76   ...         9.8        5
3           11.2              0.28   ...         9.8        6
4            7.4              0.70   ...         9.4        5

[5 rows x 12 columns]

In [3]:
wineData.quality.unique() 

array([5, 6, 7, 4, 8, 3])

Looks like wine quality in this dataset ranges from 3 to 8. Let's look at the distribution:

In [ ]:
#wine as 'good'(1) if its quality is larger than or equal to 7, and 'not good'(0) otherwise. 

In [5]:
wineData['category'] = wineData['quality'] >= 7
wineData.head()

fixed acidity  volatile acidity    ...     quality  category
0            7.4              0.70    ...           5     False
1            7.8              0.88    ...           5     False
2            7.8              0.76    ...           5     False
3           11.2              0.28    ...           6     False
4            7.4              0.70    ...           5     False

[5 rows x 13 columns]

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
X = wineData[['fixed acidity','volatile acidity']].values
y = wineData['category'].values.astype(np.int)

scaler = StandardScaler()
Xstan = scaler.fit_transform(X)

#for plot
dataStan=pd.DataFrame()
dataStan['fixed acidity(stan)']=Xstan[:,0]
dataStan['volatile acidity(stan)']=Xstan[:,1]
dataStan['category']=y
dataStan.head()

fixed acidity(stan)  volatile acidity(stan)  category
0            -0.528360                0.961877         0
1            -0.298547                1.967442         0
2            -0.298547                1.297065         0
3             1.654856               -1.384443         0
4            -0.528360                0.961877         0

In [8]:
logReg = LogisticRegression()
logReg.fit(Xstan,y)
logReg.coef_, logReg.intercept_

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(array([[ 0.11854528, -0.98843455]]), array([-2.16578589]))

In [9]:
logReg.predict_proba(Xstan)

array([[0.96004294, 0.03995706],
       [0.98441694, 0.01558306],
       [0.97020716, 0.02979284],
       ...,
       [0.90069194, 0.09930806],
       [0.95155331, 0.04844669],
       [0.75417336, 0.24582664]])

In [10]:
yhat = logReg.predict(Xstan)
dataStan['predict']=yhat
dataStan.head()

fixed acidity(stan)  volatile acidity(stan)  category  predict
0            -0.528360                0.961877         0        0
1            -0.298547                1.967442         0        0
2            -0.298547                1.297065         0        0
3             1.654856               -1.384443         0        0
4            -0.528360                0.961877         0        0

In [13]:
#all columns
X = wineData[wineData.columns[0:11]].values

In [14]:
y = wineData['category'].values.astype(np.int)

scaler = StandardScaler()
Xstan = scaler.fit_transform(X)

In [15]:
dataStan=pd.DataFrame(data = Xstan, columns = wineData.columns[0:11])
dataStan['category']=y
dataStan.head()

fixed acidity  volatile acidity    ...      alcohol  category
0      -0.528360          0.961877    ...    -0.960246         0
1      -0.298547          1.967442    ...    -0.584777         0
2      -0.298547          1.297065    ...    -0.584777         0
3       1.654856         -1.384443    ...    -0.584777         0
4      -0.528360          0.961877    ...    -0.960246         0

[5 rows x 12 columns]

In [16]:
logReg = LogisticRegression()
logReg.fit(Xstan,y)
logReg.intercept_, logReg.coef_

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(array([-2.74747858]),
 array([[ 0.44832583, -0.44980744,  0.11472068,  0.32097755, -0.39780712,
          0.09977471, -0.51371325, -0.46204675,  0.02447459,  0.61383442,
          0.79008202]]))

In [21]:
yhat = logReg.predict(Xstan)
dataStan['predict'] = yhat
dataStan.head()

fixed acidity  volatile acidity   ...     category  predict
0      -0.528360          0.961877   ...            0        0
1      -0.298547          1.967442   ...            0        0
2      -0.298547          1.297065   ...            0        0
3       1.654856         -1.384443   ...            0        0
4      -0.528360          0.961877   ...            0        0

[5 rows x 13 columns]